- name: backend project 
  hosts: backend
  become: yes
  vars:
   
  tasks:
  - name: disable the nodejs module
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable the nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  #- name: install nodejs
  #  ansible.builtin.command: dnf install nodejs -y
  #- name: create the user expense 
  # ansible.builtin.command: useradd expense
  - name: install the nodejs
    ansible.builtin.package: #works for all distros
     name: nodejs
     state: installed
  - name: create the user expense
    ansible.builtin.user:   #works for all distros
     name: expense
  - name: create a app directory 
    ansible.builtin.file:
     path: /app
     state: directory
  - name: download the backend code 
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     dest: /tmp/backend.zip 
  - name: unzip the code 
    ansible.builtin.unarchive:
     src: /tmp/backend.zip
     dest: /app
     remote_src: yes   
  - name: install the npm 
    ansible.builtin.command: npm install 
    args:
     chdir: /app 
  - name: copy the backend service 
    ansible.builtin.copy:
     src: backend.service
     dest: /etc/systemd/system/backend.service
                  