- name: frontend server 
  hosts: frontend
  become: yes
  vars:

  tasks:
  - name: install the nginx server 
    ansible.builtin.package:
     name: nginx 
     state: installed
  - name: start and enable the nginx 
    ansible.builtin.service:
     name: nginx
     state: started 
     enabled: yes 
  - name: to remove nginx files 
    ansible.builtin.command: rm -rf /usr/share/nginx/html/*
  #- name: download the frotend code 
   # ansible.builtin.get_url:
    # url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
     #dest: /tmp/frontend.zip
  #- name: extarct the frontend code 
    #ansible.builtin.unarchive:
     #src: /tmp/frontend.zip
     #dest: /usr/share/nginx/html
     #remote_src: yes 

