- name: frontend server 
  hosts: frontend
  become: yes
  vars:

  tasks:
  - name: install the nginx server 
    ansible.builtin.package:
     name: nginx 
     state: installed
  - name: start and enable the nginx 
    ansible.builtin.service:
     name: nginx
     state: started 
     enabled: yes 
  - name: to remove nginx files 
    ansible.builtin.command: rm -rf rm -rf /usr/share/nginx/html/*
       
