- name: frontend server 
  hosts: frontend
  become: yes
  vars:

  tasks:
  - name: install the nginx server 
    ansible.builtin.package:
     name: nginx 
     state: installed
  - name: start and enable the nginx 
    ansible.builtin.service:
     name: nginx
     state: started 
     enabled: yes 
  - name: Find all files and directories inside /usr/share/nginx/html
    ansible.builtin.find:
        paths: "/usr/share/nginx/html"
        file_type: any
        recurse: yes
    register: found_items

  -  name: Display found items
    debug:
        msg: "{{ item.path }} (type: {{ item.file_type }})"
    loop: "{{ found_items.files + found_items.dirs }}"
    
  - name: Remove files and directories
    ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
    loop: "{{ found_items.files + found_items.dirs }}"      
        

 

