- name: frontend server 
  hosts: frontend
  become: yes
  vars:

  tasks:
  - name: install the nginx server 
    ansible.builtin.package:
     name: nginx 
     state: installed
  - name: start and enable the nginx 
    ansible.builtin.service:
     name: nginx
     state: started 
     enabled: yes 
  - name: Delete files and directories
    ansible.builtin.find:
     paths: "/usr/share/nginx/html"
     file_type: any 
     recurse: true
    register: collected_files 
  - name: collected files 
    ansible.builtin.debug:
     msg: "output: {{ collected_files }}"
  - name: remove collected files 
    ansible.builtin.file:
      path: "{{item.path }}"
      state: absent 
    with_items: "{{ collected_files }}"         
        

 

